model:
  base_learning_rate: 3.0e-06
  target: ldm.models.diffusion.cfm1_audio.CFM
  params:
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    mel_dim: 20
    mel_length: 750
    channels: 0
    cond_stage_trainable: True
    conditioning_key: hybrid
    monitor: val/loss_simple_ema
    scale_by_std: true
    use_ema: false
    scheduler_config:
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps:
        - 10000
        cycle_lengths:
        - 10000000000000
        f_start:
        - 1.0e-06
        f_max:
        - 1.0
        f_min:
        - 1.0
    unet_config:
      target: ldm.modules.diffusionmodules.vocal2music_moe.TxtFlagLargeImprovedDiTV2
      params:
        in_channels: 20
        ori_dim: 1024
        context_dim: 768
        hidden_size: 768
        num_heads: 8
        depth: 4
        max_len: 1500
        num_experts: 4

    first_stage_config:
      target: ldm.models.autoencoder1d.AutoencoderKL
      params:
        embed_dim: 20
        monitor: val/rec_loss
        ckpt_path: logs/2024-04-21T17-06-16_ae_accomp/bkup_ckpts/last.ckpt
        ddconfig:
          double_z: true
          in_channels: 80
          out_ch: 80
          z_channels: 20
          kernel_size: 5
          ch: 384
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_layers:
          - 3
          down_layers:
          - 0
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenTextVocalEmbedder
      params:
        version: useful_ckpts/flan-t5-large
        max_length: 80

lightning:
  callbacks:
    image_logger:
      target: main.AudioLogger
      params:
        sample_rate: 24000
        for_specs: true
        increase_log_steps: false
        batch_frequency: 5000
        max_images: 8
        melvmin: -5
        melvmax: 1.5
        vocoder_cfg:
          target: vocoder.hifigan.hifigan.HifiGAN
          params:
            vocoder_ckpt: /root/autodl-tmp/SingingDictation/checkpoints/240421-hifigan-01
  trainer:
    benchmark: True
    gradient_clip_val: 1.0
    replace_sampler_ddp: false
  modelcheckpoint:
    params:
      monitor: epoch
      mode: max
      save_top_k: 10
      every_n_epochs: 10

data:
  target: main.SpectrogramDataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 16
    main_spec_dir_path: '/root/autodl-tmp/data/manifests/vocal_to_accomp/train/v2c_0905'
    other_spec_dir_path: ''
    mel_num: 80
    drop: 0.1
    spec_crop_len: 1500
    other_condition: '/root/autodl-tmp/data/manifests/vocal_to_accomp/train/v2c_0905/midi.npy'   # codec npy path!!!
    train:
      target: ldm.data.vocal2accomp_musical_dataset.JoinSpecsTrain
      params:
        specs_dataset_cfg:
    validation:
      target: ldm.data.vocal2accomp_musical_dataset.JoinSpecsValidation
      params:
        specs_dataset_cfg:

test_dataset:
  target: ldm.data.tsvdataset.TSVDatasetStruct
  params:
    tsv_path: audiocaps_test_16000_struct2.tsv
    spec_crop_len: 1500

